apiVersion: v1
kind: ConfigMap
metadata:
  name: fsx-data-prep-map
data:
  #S3_BUCKET: s3://YOUR_S3_BUCKET_WITH_DATA
  MOUNT_PATH: /fsx-shared

---
apiVersion: v1
kind: Pod
metadata:
  name: fsx-data-prep-pod
spec:
  containers:
  - name: fsx-data-prep-pod
    image: <ECR-registry-path>/s3-fsx
    envFrom:
    - configMapRef:
        name: fsx-data-prep-map
    command: ["/bin/bash"]
    args: ["-c", "/workspace/data-prep.sh"]
    volumeMounts:
    - name: fsx-pv
      mountPath: /fsx-shared
  volumes:
  - name: fsx-pv
    persistentVolumeClaim:
      claimName: fsx-pvc
  restartPolicy: Never
